### ISSUE TITLE
git curate can't run in macos 15.7

### ISSUE THREAD

**Issue by lumm** [matt-harvey/git_curate#15] opened 2021-01-22 06:13 UTC
Traceback (most recent call last):
	8: from /usr/local/bin/git-curate:23:in `<main>'
	7: from /usr/local/bin/git-curate:23:in `load'
	6: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/exe/git-curate:5:in `<top (required)>'
	5: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/app.rb:16:in `main'
	4: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/runner.rb:29:in `run'
	3: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:70:in `local'
	2: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:88:in `branch_info'
	1: from /Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:88:in `map'
/Library/Ruby/Gems/2.6.0/gems/git_curate-1.1.2/lib/git_curate/branch.rb:93:in `block in branch_info': undefined method `upstream' for nil:NilClass (NoMethodError)

**Comment by matt-harvey** [comment] 2021-01-24 20:06
@lumm This issue appears virtually identical to the one you raised [previously](https://github.com/matt-harvey/git_curate/issues/14). On that occasion I responded that I was unable to reproduce or fix the issue [without more information on your environment and branches](https://github.com/matt-harvey/git_curate/issues/14#issuecomment-727523520). However, you never provided any of that information. And now I see you are raising essentially the same issue again, but still without providing any of the information I asked for. So the result is going to be [the same](https://github.com/matt-harvey/git_curate/issues/14#issuecomment-741581824) I'm afraid.

**Comment by matt-harvey** [comment] 2021-01-24 20:07
Duplicate of #14.

**Closed by matt-harvey** 2021-01-24 20:07 UTC
